replicaCount: 1

image:
  repository: pratikslv38/fastapi-ml
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: dockerhub-creds

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  host: yourdomain.example.com
